#!/bin/bash
#SBATCH --job-name=TrainGAT
#SBATCH --output=Log/test_risk%j.txt  # Save output to file named result_JOBID.txt
#SBATCH --ntasks=1              # Run a single task/job
#SBATCH --cpus-per-task=8       # Number of CPU cores per task
#SBATCH --mem=4G                # Total memory for the job
#SBATCH --time=01:00:00         # Time limit hh:mm:ss



# Activate the virtual environment
source venv/bin/activate

# Run the Python script
python 0.TrainingModel.py

# Deactivate the virtual environment
deactivate
